import type { Metadata } from "next";
import "./globals.css";
import { Epilogue } from "next/font/google";
import TheNavbar from "@/components/TheNavbar";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={epilogue.className}>
      <body>
        <TheNavbar />
        {children}
      </body>
    </html>
  );
}
